# Generated by Django 4.2.3 on 2023-07-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('number',), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
