# Generated by Django 4.2.2 on 2023-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_slug_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
