# Generated by Django 4.2.3 on 2023-07-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('version_name',), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='version_name',
        ),
        migrations.RemoveField(
            model_name='version',
            name='number',
        ),
    ]
