# Generated by Django 4.2.3 on 2023-08-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.version', verbose_name='версия'),
        ),
    ]
