# Generated by Django 4.2.3 on 2023-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_versions_version_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(default=0, verbose_name='номер версии'),
        ),
    ]
