# Generated by Django 4.2.3 on 2023-08-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='versions',
        ),
    ]
